Warn when not being able to get server_info
XENONnT/utilix pull request #14
Opened 2020-11-23 10:16 UTC by jorana

We have recently seen that this can cause errors:
https://xenonnt.slack.com/archives/C016DM0JPK9/p1605866361323700

This can be avoided by the read-preference, therefore we may just raise a warning rather than an Error (what I did first). Let me know if you think this is still necessary.

2020-11-23 17:40 UTC, ershockley approved these changes
Thanks @jorana! This connection check is definitely useful, but I think the warning should not include the stuff about secondaryPreferred since by using this function this flag is passed automatically. I would just recommend to have it say something like "Cannot connect to the database, please check your config at {path to config}" or similar. I'm still approving since this is a super minor thing.

2020-11-23 20:02 UTC, ershockley requested changes
@jorana sorry for not testing enough before approving before. I hope my suggested changes in #15 make sense. The secondaryPreferred thing is not a problem with utilix itself, so I don't think it should be focusing on that. But testing the collection before returning it can't hurt.

2020-11-25 12:54 UTC, jorana commented
@ershockley , ready to merge?

2020-11-25 17:07 UTC, ershockley commented
Yes sorry got sidetracked. Thanks @jorana!

2020-11-25 17:07 UTC, merged