Cache mongo client
XENONnT/utilix pull request #50
Opened 2021-07-08 00:26 UTC by ershockley

This caches the Mongo client so that we don't create multiple such objects, as warned against [here](https://pymongo.readthedocs.io/en/stable/faq.html). It also allows for (but doesn't require) 3 more config options in the xenon_config: 

```
max_pool_size=<maxPoolSize>
socket_timeout=<socketTimeoutMS>
connect_timeout=<connectTimeoutMS>
```

These have default values hardcoded.

2021-07-08 05:18 UTC, jmosbacher requested changes
Hi, looks good. 
I would change the dictionary key so the function stays consistent (example inline)

2021-07-08 05:18 UTC, jmosbacher commented on utilix/rundb.py
> +    global MONGO_CLIENTS
Declaring MONGO_CLIENTS as global is not needed, since you only change its contents and not the object the name is bound to in the global context.

2021-07-08 05:18 UTC, jmosbacher commented on utilix/rundb.py
> +        MONGO_CLIENTS[experiment] = pymongo.MongoClient(uri, readPreference='secondaryPreferred',
Storing the clients under experiment name is incompatible with the function signature. Either store a client for any uri or change to signature to disallow passing your own username/pass. I would suggest:
```python
uri = f"mongodb://{user}:{password}@{url}"
if (experiment,uri) not in MONGO_CLIENTS:
    MONGO_CLIENTS[(experiment,uri)] = pymongo.MongoClient(...
db = MONGO_CLIENTS[(experiment,uri)][database]

```

2021-07-23 12:35 UTC, jmosbacher commented
@ershockley I changed the cache key to the uri, do you have any use cases to test it on and make sure its works?

2021-07-23 12:39 UTC, jmosbacher approved these changes
I think we should run some quick tests by loading some data with this branch and merge asap

2021-07-23 18:02 UTC, ershockley commented
Thanks @jmosbacher! Looks good after some very simple tests.

2021-07-23 18:09 UTC, merged